apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: authorization
    color: blue
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
