apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-${COLOR}-${VERSION}
  namespace: ${NAMESPACE}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-${COLOR}
      color: ${COLOR}
      version: ${VERSION}
  template:
    metadata:
      labels:
        app: backend-${COLOR}
        color: ${COLOR}
        version: ${VERSION}
    spec:
      containers:
        - name: backend
          image: ${IMAGE}
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: ${VERSION}
            - name: DB_HOST
              value: database-2.cgpam6asi9ot.us-east-1.rds.amazonaws.com
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: password
            - name: DB_DATABASE
              value: weightTracker
