apiVersion: v1
kind: Service
metadata:
  name: backend-service-${COLOR}-${VERSION}
  namespace: ${NAMESPACE}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/health"
spec:
  selector:
    app: backend-${COLOR}
    color: ${COLOR}
    version: ${VERSION}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
