apiVersion: v1
kind: Service
metadata:
  name: frontend-service-${COLOR}
  namespace: ${NAMESPACE}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  type: ClusterIP
  selector:
    app: frontend-${COLOR}
    color: ${COLOR}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
