apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ${NAMESPACE}
data:
  config.json: |
    {
      "REACT_APP_API_BASE_URL": "http://authorization-service.${NAMESPACE}.svc.cluster.local:8001",
      "REACT_APP_BACKEND_BASE_URL": "http://backend-service.${NAMESPACE}.svc.cluster.local:8000"
    }
